# syntax=docker/dockerfile:1

FROM python:3

WORKDIR /usr/src/app/bot_stalker

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

CMD [ "python3", "-m" , "bot_stalker.py"]